### ISSUE TITLE
The documentation does not describe where to configure the headers in FF

### ISSUE THREAD

**Issue by anneb** [loreii/HeaderTool#6]
Firefox has a hidden menu, to be found with the F10 key. After installing the plugin, you have to open the sidebar using the hidden menu View->Sidebar->Header Tool

This is not obvious (at least not to me).

So I propose an update for Readme.md (At this laptop, I do not have a git client installed,  so I can't  fork, checkout, update, send a pull request etc.):

Header Tool
============
You can easily _modify header_ on each HTTP request from **Mozilla Firefox**.
The tool is based on the same main stream idea of modify header but uses a more simple text editor interface and it is quicker to edit, store and save for multiple and repeated test cases.

**Download from** [addons.mozilla.org](https://addons.mozilla.org/it/firefox/addon/header-tool/)

Using this tool you can easily modify headers on each HTTP request from **Mozilla Firefox**.
The tool is based on the same main stream idea of modify header but uses a simpler text editor interface and it is quicker to edit, store and save for multiple and repeated test cases. For example, you can save your header in a simple txt file and reuse it by just copying _crtl+C_ and pasting _crtl+V_ it to the Mozilla Firefox Header Tool sidebar (F10->Menu->View->Side Bar->Header Tool). If you find an issue or you have an idea on how improve this plugin please pen a ticket, as soon as possible i'll try to fix it. If you are a developer don't hesitate to send to me the patch

**Comment by loreii** [comment]
Hi anneb,
Thank for your contribution i merged it today :)
