### ISSUE TITLE
HeaderTool was broken by Firefox 46

### ISSUE THREAD

**Issue by norstbox** [loreii/HeaderTool#7]
FF46 [changelog](https://developer.mozilla.org/en-US/Firefox/Releases/46) says:
> [JS1.7/JS1.8 (legacy) array comprehensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions#Differences_to_the_older_JS1.7JS1.8_comprehensions) have been removed ([bug 1220564](https://bugzilla.mozilla.org/show_bug.cgi?id=1220564)).

So [`headertoolModule.js:329`](https://github.com/loreii/HeaderTool/blob/63471ea72fd3697f2769f83c619a802a58d961be/modules/headertoolModule.js#L329) causes an error.

**Comment by ulkas** [comment]
i confirm this on a fresh new instance of ff 46 it does not work.
also when upgrading older ff 45 to 46 it stops working

**Comment by norstbox** [comment]
@ulkas we need to fix only that line.

**Comment by Marsu31** [comment]
Up !
We need this please :-)
I have tried the quick syntax fix but it doesn't work :-/
Is the project dead ?
